.PHONY: clean All

All:
	@echo "==========Building project:[ CommandLineArgs - Debug ]=========="
	@cd "CommandLineArgs" && "$(MAKE)" -f  "CommandLineArgs.mk"
clean:
	@echo "==========Cleaning project:[ CommandLineArgs - Debug ]----------"
	@cd "CommandLineArgs" && "$(MAKE)" -f  "CommandLineArgs.mk" clean
